<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Http\Request;

class Authenticate extends Middleware
{

    protected function redirectTo(Request $request)
    {
        return parent::redirectTo($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param $request
     * @param Closure $next
     * @param string ...$guards
     * @return mixed
     * @throws AuthenticationException
     */
    public function handle($request, Closure $next, ...$guards): mixed
    {
        return parent::handle($request, $next, ...$guards);
    }
}
